# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scgui.ui'
#
# Created: Mon Feb 20 15:56:15 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(350, 460)
        MainWindow.setMinimumSize(QtCore.QSize(350, 460))
        MainWindow.setMaximumSize(QtCore.QSize(350, 460))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/counterstrike-5.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8(""))
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.settingsTab = QtGui.QWidget()
        self.settingsTab.setObjectName(_fromUtf8("settingsTab"))
        self.groupBox = QtGui.QGroupBox(self.settingsTab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 311, 51))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.BTN_steamname = QtGui.QPushButton(self.groupBox)
        self.BTN_steamname.setGeometry(QtCore.QRect(230, 20, 71, 22))
        self.BTN_steamname.setObjectName(_fromUtf8("BTN_steamname"))
        self.steaminput = QtGui.QLineEdit(self.groupBox)
        self.steaminput.setGeometry(QtCore.QRect(30, 20, 191, 20))
        self.steaminput.setText(_fromUtf8(""))
        self.steaminput.setFrame(True)
        self.steaminput.setDragEnabled(True)
        self.steaminput.setObjectName(_fromUtf8("steaminput"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 21, 21))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/steam_icon.png")))
        self.label.setObjectName(_fromUtf8("label"))
        self.steamstatus = QtGui.QLabel(self.settingsTab)
        self.steamstatus.setGeometry(QtCore.QRect(10, 350, 311, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.steamstatus.setFont(font)
        self.steamstatus.setStyleSheet(_fromUtf8("color: rgb(170, 170, 0);"))
        self.steamstatus.setText(_fromUtf8(""))
        self.steamstatus.setTextFormat(QtCore.Qt.AutoText)
        self.steamstatus.setScaledContents(False)
        self.steamstatus.setAlignment(QtCore.Qt.AlignCenter)
        self.steamstatus.setWordWrap(False)
        self.steamstatus.setObjectName(_fromUtf8("steamstatus"))
        self.webView = QtWebKit.QWebView(self.settingsTab)
        self.webView.setGeometry(QtCore.QRect(10, 70, 311, 281))
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("http://stunjelly.com/scgui/app/")))
        self.webView.setZoomFactor(1.0)
        self.webView.setObjectName(_fromUtf8("webView"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/gear_in.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.settingsTab, icon1, _fromUtf8(""))
        self.skinsTab = QtGui.QWidget()
        self.skinsTab.setObjectName(_fromUtf8("skinsTab"))
        self.BTN_uninstallSkin = QtGui.QPushButton(self.skinsTab)
        self.BTN_uninstallSkin.setEnabled(True)
        self.BTN_uninstallSkin.setGeometry(QtCore.QRect(260, 209, 61, 23))
        self.BTN_uninstallSkin.setAutoFillBackground(False)
        self.BTN_uninstallSkin.setCheckable(False)
        self.BTN_uninstallSkin.setObjectName(_fromUtf8("BTN_uninstallSkin"))
        self.BTN_skinFolder = QtGui.QPushButton(self.skinsTab)
        self.BTN_skinFolder.setGeometry(QtCore.QRect(98, 347, 70, 23))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/folders_explorer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_skinFolder.setIcon(icon2)
        self.BTN_skinFolder.setObjectName(_fromUtf8("BTN_skinFolder"))
        self.comboBox_skins = QtGui.QComboBox(self.skinsTab)
        self.comboBox_skins.setGeometry(QtCore.QRect(70, 180, 181, 21))
        self.comboBox_skins.setObjectName(_fromUtf8("comboBox_skins"))
        self.skinName = QtGui.QLabel(self.skinsTab)
        self.skinName.setGeometry(QtCore.QRect(10, 10, 311, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.skinName.setFont(font)
        self.skinName.setObjectName(_fromUtf8("skinName"))
        self.skinAuthor = QtGui.QLabel(self.skinsTab)
        self.skinAuthor.setGeometry(QtCore.QRect(10, 30, 311, 20))
        font = QtGui.QFont()
        font.setItalic(False)
        self.skinAuthor.setFont(font)
        self.skinAuthor.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.skinAuthor.setWordWrap(False)
        self.skinAuthor.setObjectName(_fromUtf8("skinAuthor"))
        self.skinVersion = QtGui.QLabel(self.skinsTab)
        self.skinVersion.setGeometry(QtCore.QRect(70, 200, 181, 21))
        self.skinVersion.setObjectName(_fromUtf8("skinVersion"))
        self.skinVersionLabel = QtGui.QLabel(self.skinsTab)
        self.skinVersionLabel.setGeometry(QtCore.QRect(10, 200, 51, 21))
        self.skinVersionLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.skinVersionLabel.setObjectName(_fromUtf8("skinVersionLabel"))
        self.skinTypeLabel = QtGui.QLabel(self.skinsTab)
        self.skinTypeLabel.setGeometry(QtCore.QRect(10, 220, 51, 21))
        self.skinTypeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.skinTypeLabel.setObjectName(_fromUtf8("skinTypeLabel"))
        self.skinType = QtGui.QLabel(self.skinsTab)
        self.skinType.setGeometry(QtCore.QRect(70, 220, 181, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.skinType.setFont(font)
        self.skinType.setFocusPolicy(QtCore.Qt.NoFocus)
        self.skinType.setToolTip(_fromUtf8(""))
        self.skinType.setStatusTip(_fromUtf8(""))
        self.skinType.setScaledContents(False)
        self.skinType.setOpenExternalLinks(False)
        self.skinType.setObjectName(_fromUtf8("skinType"))
        self.SkinPreviewImage = QtGui.QLabel(self.skinsTab)
        self.SkinPreviewImage.setGeometry(QtCore.QRect(8, 50, 311, 121))
        self.SkinPreviewImage.setAutoFillBackground(False)
        self.SkinPreviewImage.setFrameShape(QtGui.QFrame.NoFrame)
        self.SkinPreviewImage.setFrameShadow(QtGui.QFrame.Plain)
        self.SkinPreviewImage.setLineWidth(0)
        self.SkinPreviewImage.setText(_fromUtf8(""))
        self.SkinPreviewImage.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/default.jpg")))
        self.SkinPreviewImage.setScaledContents(True)
        self.SkinPreviewImage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SkinPreviewImage.setObjectName(_fromUtf8("SkinPreviewImage"))
        self.BTN_installSkin = QtGui.QPushButton(self.skinsTab)
        self.BTN_installSkin.setEnabled(True)
        self.BTN_installSkin.setGeometry(QtCore.QRect(260, 179, 61, 23))
        self.BTN_installSkin.setAutoFillBackground(False)
        self.BTN_installSkin.setCheckable(False)
        self.BTN_installSkin.setObjectName(_fromUtf8("BTN_installSkin"))
        self.BTN_cstrikeFolder = QtGui.QPushButton(self.skinsTab)
        self.BTN_cstrikeFolder.setGeometry(QtCore.QRect(168, 347, 70, 23))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_cstrikeFolder.setIcon(icon3)
        self.BTN_cstrikeFolder.setObjectName(_fromUtf8("BTN_cstrikeFolder"))
        self.skinNameLabel = QtGui.QLabel(self.skinsTab)
        self.skinNameLabel.setGeometry(QtCore.QRect(10, 180, 51, 20))
        self.skinNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.skinNameLabel.setObjectName(_fromUtf8("skinNameLabel"))
        self.BTN_launchCSSpec = QtGui.QPushButton(self.skinsTab)
        self.BTN_launchCSSpec.setGeometry(QtCore.QRect(8, 347, 90, 23))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/movies.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_launchCSSpec.setIcon(icon4)
        self.BTN_launchCSSpec.setObjectName(_fromUtf8("BTN_launchCSSpec"))
        self.skinDescription = QtGui.QPlainTextEdit(self.skinsTab)
        self.skinDescription.setGeometry(QtCore.QRect(8, 244, 311, 100))
        self.skinDescription.setObjectName(_fromUtf8("skinDescription"))
        self.tabWidget.addTab(self.skinsTab, _fromUtf8(""))
        self.configTab = QtGui.QWidget()
        self.configTab.setObjectName(_fromUtf8("configTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.configTab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tableView = QtGui.QTableView(self.configTab)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.verticalLayout_3.addWidget(self.tableView)
        self.BTN_refreshCfg = QtGui.QPushButton(self.configTab)
        self.BTN_refreshCfg.setEnabled(True)
        self.BTN_refreshCfg.setObjectName(_fromUtf8("BTN_refreshCfg"))
        self.verticalLayout_3.addWidget(self.BTN_refreshCfg)
        self.BTN_updateCfg = QtGui.QPushButton(self.configTab)
        self.BTN_updateCfg.setEnabled(True)
        self.BTN_updateCfg.setObjectName(_fromUtf8("BTN_updateCfg"))
        self.verticalLayout_3.addWidget(self.BTN_updateCfg)
        self.tabWidget.addTab(self.configTab, _fromUtf8(""))
        self.teamsTab = QtGui.QWidget()
        self.teamsTab.setObjectName(_fromUtf8("teamsTab"))
        self.teamgrouphome = QtGui.QGroupBox(self.teamsTab)
        self.teamgrouphome.setEnabled(True)
        self.teamgrouphome.setGeometry(QtCore.QRect(10, 10, 311, 111))
        self.teamgrouphome.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.teamgrouphome.setFlat(False)
        self.teamgrouphome.setCheckable(False)
        self.teamgrouphome.setObjectName(_fromUtf8("teamgrouphome"))
        self.Box_t1name = QtGui.QLineEdit(self.teamgrouphome)
        self.Box_t1name.setEnabled(True)
        self.Box_t1name.setGeometry(QtCore.QRect(82, 20, 211, 20))
        self.Box_t1name.setToolTip(_fromUtf8(""))
        self.Box_t1name.setWhatsThis(_fromUtf8(""))
        self.Box_t1name.setObjectName(_fromUtf8("Box_t1name"))
        self.t1nameLabel = QtGui.QLabel(self.teamgrouphome)
        self.t1nameLabel.setEnabled(True)
        self.t1nameLabel.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.t1nameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t1nameLabel.setObjectName(_fromUtf8("t1nameLabel"))
        self.Box_t1url = QtGui.QLineEdit(self.teamgrouphome)
        self.Box_t1url.setEnabled(True)
        self.Box_t1url.setGeometry(QtCore.QRect(82, 50, 211, 20))
        self.Box_t1url.setObjectName(_fromUtf8("Box_t1url"))
        self.t1urlLabel = QtGui.QLabel(self.teamgrouphome)
        self.t1urlLabel.setEnabled(True)
        self.t1urlLabel.setGeometry(QtCore.QRect(10, 50, 61, 21))
        self.t1urlLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t1urlLabel.setObjectName(_fromUtf8("t1urlLabel"))
        self.comboBox_t1flag = QtGui.QComboBox(self.teamgrouphome)
        self.comboBox_t1flag.setEnabled(True)
        self.comboBox_t1flag.setGeometry(QtCore.QRect(82, 80, 211, 21))
        self.comboBox_t1flag.setEditable(False)
        self.comboBox_t1flag.setFrame(True)
        self.comboBox_t1flag.setObjectName(_fromUtf8("comboBox_t1flag"))
        self.t1flagLabel = QtGui.QLabel(self.teamgrouphome)
        self.t1flagLabel.setEnabled(True)
        self.t1flagLabel.setGeometry(QtCore.QRect(10, 80, 61, 21))
        self.t1flagLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t1flagLabel.setObjectName(_fromUtf8("t1flagLabel"))
        self.teamgroupaway = QtGui.QGroupBox(self.teamsTab)
        self.teamgroupaway.setEnabled(True)
        self.teamgroupaway.setGeometry(QtCore.QRect(10, 130, 311, 111))
        self.teamgroupaway.setObjectName(_fromUtf8("teamgroupaway"))
        self.Box_t2name = QtGui.QLineEdit(self.teamgroupaway)
        self.Box_t2name.setEnabled(True)
        self.Box_t2name.setGeometry(QtCore.QRect(82, 20, 211, 20))
        self.Box_t2name.setObjectName(_fromUtf8("Box_t2name"))
        self.t2nameLabel = QtGui.QLabel(self.teamgroupaway)
        self.t2nameLabel.setEnabled(True)
        self.t2nameLabel.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.t2nameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t2nameLabel.setObjectName(_fromUtf8("t2nameLabel"))
        self.Box_t2url = QtGui.QLineEdit(self.teamgroupaway)
        self.Box_t2url.setEnabled(True)
        self.Box_t2url.setGeometry(QtCore.QRect(82, 50, 211, 20))
        self.Box_t2url.setObjectName(_fromUtf8("Box_t2url"))
        self.t2urlLabel = QtGui.QLabel(self.teamgroupaway)
        self.t2urlLabel.setEnabled(True)
        self.t2urlLabel.setGeometry(QtCore.QRect(10, 50, 61, 21))
        self.t2urlLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t2urlLabel.setObjectName(_fromUtf8("t2urlLabel"))
        self.comboBox_t2flag = QtGui.QComboBox(self.teamgroupaway)
        self.comboBox_t2flag.setEnabled(True)
        self.comboBox_t2flag.setGeometry(QtCore.QRect(82, 80, 211, 21))
        self.comboBox_t2flag.setObjectName(_fromUtf8("comboBox_t2flag"))
        self.t2flagLabel = QtGui.QLabel(self.teamgroupaway)
        self.t2flagLabel.setEnabled(True)
        self.t2flagLabel.setGeometry(QtCore.QRect(10, 80, 61, 21))
        self.t2flagLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t2flagLabel.setObjectName(_fromUtf8("t2flagLabel"))
        self.BTN_updateTeams = QtGui.QPushButton(self.teamsTab)
        self.BTN_updateTeams.setEnabled(True)
        self.BTN_updateTeams.setGeometry(QtCore.QRect(220, 340, 101, 23))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/hammer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_updateTeams.setIcon(icon5)
        self.BTN_updateTeams.setObjectName(_fromUtf8("BTN_updateTeams"))
        self.BTN_refreshteams = QtGui.QPushButton(self.teamsTab)
        self.BTN_refreshteams.setGeometry(QtCore.QRect(10, 340, 101, 23))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/arrow_refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_refreshteams.setIcon(icon6)
        self.BTN_refreshteams.setObjectName(_fromUtf8("BTN_refreshteams"))
        self.BTN_swapSides = QtGui.QPushButton(self.teamsTab)
        self.BTN_swapSides.setEnabled(True)
        self.BTN_swapSides.setGeometry(QtCore.QRect(120, 340, 91, 23))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/magic_wand_2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_swapSides.setIcon(icon7)
        self.BTN_swapSides.setObjectName(_fromUtf8("BTN_swapSides"))
        self.playergroup = QtGui.QGroupBox(self.teamsTab)
        self.playergroup.setEnabled(True)
        self.playergroup.setGeometry(QtCore.QRect(10, 250, 311, 81))
        self.playergroup.setObjectName(_fromUtf8("playergroup"))
        self.t2nameLabel_2 = QtGui.QLabel(self.playergroup)
        self.t2nameLabel_2.setEnabled(True)
        self.t2nameLabel_2.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.t2nameLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t2nameLabel_2.setObjectName(_fromUtf8("t2nameLabel_2"))
        self.Box_playername = QtGui.QLineEdit(self.playergroup)
        self.Box_playername.setEnabled(True)
        self.Box_playername.setGeometry(QtCore.QRect(80, 20, 211, 20))
        self.Box_playername.setObjectName(_fromUtf8("Box_playername"))
        self.comboBox_playerflag = QtGui.QComboBox(self.playergroup)
        self.comboBox_playerflag.setEnabled(True)
        self.comboBox_playerflag.setGeometry(QtCore.QRect(80, 50, 211, 21))
        self.comboBox_playerflag.setObjectName(_fromUtf8("comboBox_playerflag"))
        self.t2flagLabel_2 = QtGui.QLabel(self.playergroup)
        self.t2flagLabel_2.setEnabled(True)
        self.t2flagLabel_2.setGeometry(QtCore.QRect(10, 50, 61, 21))
        self.t2flagLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t2flagLabel_2.setObjectName(_fromUtf8("t2flagLabel_2"))
        self.tabWidget.addTab(self.teamsTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Config = QtGui.QAction(MainWindow)
        self.actionLoad_Config.setEnabled(False)
        self.actionLoad_Config.setObjectName(_fromUtf8("actionLoad_Config"))
        self.actionSave_Config = QtGui.QAction(MainWindow)
        self.actionSave_Config.setEnabled(False)
        self.actionSave_Config.setObjectName(_fromUtf8("actionSave_Config"))
        self.actionCheck_for_Updates = QtGui.QAction(MainWindow)
        self.actionCheck_for_Updates.setEnabled(False)
        self.actionCheck_for_Updates.setObjectName(_fromUtf8("actionCheck_for_Updates"))
        self.actionWebsite = QtGui.QAction(MainWindow)
        self.actionWebsite.setObjectName(_fromUtf8("actionWebsite"))
        self.actionPrefrences = QtGui.QAction(MainWindow)
        self.actionPrefrences.setObjectName(_fromUtf8("actionPrefrences"))
        self.actionDevelopers_Blog = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/tumblr.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDevelopers_Blog.setIcon(icon8)
        self.actionDevelopers_Blog.setObjectName(_fromUtf8("actionDevelopers_Blog"))
        self.actionDonate = QtGui.QAction(MainWindow)
        self.actionDonate.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/award_star_gold_3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDonate.setIcon(icon9)
        self.actionDonate.setObjectName(_fromUtf8("actionDonate"))
        self.actionSet_Steam_Account_Name = QtGui.QAction(MainWindow)
        self.actionSet_Steam_Account_Name.setEnabled(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/steam_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSet_Steam_Account_Name.setIcon(icon10)
        self.actionSet_Steam_Account_Name.setObjectName(_fromUtf8("actionSet_Steam_Account_Name"))
        self.actionCinema_Mode = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/hd_720.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCinema_Mode.setIcon(icon11)
        self.actionCinema_Mode.setObjectName(_fromUtf8("actionCinema_Mode"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionUninstall_Current = QtGui.QAction(MainWindow)
        self.actionUninstall_Current.setObjectName(_fromUtf8("actionUninstall_Current"))
        self.actionOpen_Skins_Folder = QtGui.QAction(MainWindow)
        self.actionOpen_Skins_Folder.setObjectName(_fromUtf8("actionOpen_Skins_Folder"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionLoad_Config)
        self.menuFile.addAction(self.actionSave_Config)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionWebsite)
        self.menuHelp.addAction(self.actionDevelopers_Blog)
        self.menuHelp.addAction(self.actionDonate)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setStatusTip(QtGui.QApplication.translate("MainWindow", "ShoutCasters Graphical User Interface Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Account", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_steamname.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.steaminput.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Please enter your steam name here", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_uninstallSkin.setToolTip(QtGui.QApplication.translate("MainWindow", "Remove the current skin", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_uninstallSkin.setStatusTip(QtGui.QApplication.translate("MainWindow", "Remove the current skin", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_uninstallSkin.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_skinFolder.setToolTip(QtGui.QApplication.translate("MainWindow", "Open the skins folder in Explorer", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_skinFolder.setStatusTip(QtGui.QApplication.translate("MainWindow", "Open the skins folder in Explorer", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_skinFolder.setText(QtGui.QApplication.translate("MainWindow", "Skins", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_skins.setToolTip(QtGui.QApplication.translate("MainWindow", "Choose a skin from this menu", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_skins.setStatusTip(QtGui.QApplication.translate("MainWindow", "Choose a skin from this menu", None, QtGui.QApplication.UnicodeUTF8))
        self.skinName.setText(QtGui.QApplication.translate("MainWindow", "Base", None, QtGui.QApplication.UnicodeUTF8))
        self.skinAuthor.setText(QtGui.QApplication.translate("MainWindow", "author", None, QtGui.QApplication.UnicodeUTF8))
        self.skinVersion.setText(QtGui.QApplication.translate("MainWindow", "version", None, QtGui.QApplication.UnicodeUTF8))
        self.skinVersionLabel.setText(QtGui.QApplication.translate("MainWindow", "Version", None, QtGui.QApplication.UnicodeUTF8))
        self.skinTypeLabel.setText(QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.skinType.setText(QtGui.QApplication.translate("MainWindow", "type", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_installSkin.setToolTip(QtGui.QApplication.translate("MainWindow", "Click to install the selected skin", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_installSkin.setStatusTip(QtGui.QApplication.translate("MainWindow", "Click to install the selected skin", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_installSkin.setText(QtGui.QApplication.translate("MainWindow", "Install", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_cstrikeFolder.setToolTip(QtGui.QApplication.translate("MainWindow", "Open your cstrike folder in explorer", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_cstrikeFolder.setStatusTip(QtGui.QApplication.translate("MainWindow", "Open your cstrike folder in explorer", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_cstrikeFolder.setText(QtGui.QApplication.translate("MainWindow", "cstrike", None, QtGui.QApplication.UnicodeUTF8))
        self.skinNameLabel.setText(QtGui.QApplication.translate("MainWindow", "Skin", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_launchCSSpec.setToolTip(QtGui.QApplication.translate("MainWindow", "Launch CS:Source in Movie Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_launchCSSpec.setStatusTip(QtGui.QApplication.translate("MainWindow", "Launch CS:Source in Movie Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_launchCSSpec.setText(QtGui.QApplication.translate("MainWindow", "Launch CS", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.skinsTab), QtGui.QApplication.translate("MainWindow", "Skins", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_refreshCfg.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_updateCfg.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.configTab), QtGui.QApplication.translate("MainWindow", "Config", None, QtGui.QApplication.UnicodeUTF8))
        self.teamgrouphome.setTitle(QtGui.QApplication.translate("MainWindow", "Home Team", None, QtGui.QApplication.UnicodeUTF8))
        self.Box_t1name.setStatusTip(QtGui.QApplication.translate("MainWindow", "Enter the Counter-Terrorist team name", None, QtGui.QApplication.UnicodeUTF8))
        self.Box_t1name.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Counter-Terrorists", None, QtGui.QApplication.UnicodeUTF8))
        self.t1nameLabel.setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.Box_t1url.setStatusTip(QtGui.QApplication.translate("MainWindow", "Enter the text you want under the team name", None, QtGui.QApplication.UnicodeUTF8))
        self.t1urlLabel.setText(QtGui.QApplication.translate("MainWindow", "Website", None, QtGui.QApplication.UnicodeUTF8))
        self.t1flagLabel.setText(QtGui.QApplication.translate("MainWindow", "Flag/Logo", None, QtGui.QApplication.UnicodeUTF8))
        self.teamgroupaway.setTitle(QtGui.QApplication.translate("MainWindow", "Away Team", None, QtGui.QApplication.UnicodeUTF8))
        self.Box_t2name.setStatusTip(QtGui.QApplication.translate("MainWindow", "Enter the Terrorist team name", None, QtGui.QApplication.UnicodeUTF8))
        self.Box_t2name.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Terrorists", None, QtGui.QApplication.UnicodeUTF8))
        self.t2nameLabel.setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.Box_t2url.setStatusTip(QtGui.QApplication.translate("MainWindow", "Enter the text you want under the team name", None, QtGui.QApplication.UnicodeUTF8))
        self.t2urlLabel.setText(QtGui.QApplication.translate("MainWindow", "Website", None, QtGui.QApplication.UnicodeUTF8))
        self.t2flagLabel.setText(QtGui.QApplication.translate("MainWindow", "Flag/Logo", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_updateTeams.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_refreshteams.setText(QtGui.QApplication.translate("MainWindow", "Refresh Data", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_swapSides.setText(QtGui.QApplication.translate("MainWindow", "Swap Teams", None, QtGui.QApplication.UnicodeUTF8))
        self.playergroup.setTitle(QtGui.QApplication.translate("MainWindow", "Player Bar", None, QtGui.QApplication.UnicodeUTF8))
        self.t2nameLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Full Name", None, QtGui.QApplication.UnicodeUTF8))
        self.Box_playername.setStatusTip(QtGui.QApplication.translate("MainWindow", "Enter the Terrorist team name", None, QtGui.QApplication.UnicodeUTF8))
        self.Box_playername.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Edward \'KLUTCH\' Knowles", None, QtGui.QApplication.UnicodeUTF8))
        self.t2flagLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Flag", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.teamsTab), QtGui.QApplication.translate("MainWindow", "Teams", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Config.setText(QtGui.QApplication.translate("MainWindow", "Load Config", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Config.setText(QtGui.QApplication.translate("MainWindow", "Save Config", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCheck_for_Updates.setText(QtGui.QApplication.translate("MainWindow", "Check for Updates", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWebsite.setText(QtGui.QApplication.translate("MainWindow", "Website", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrefrences.setText(QtGui.QApplication.translate("MainWindow", "Steam Name", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDevelopers_Blog.setText(QtGui.QApplication.translate("MainWindow", "Developers Blog", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDonate.setText(QtGui.QApplication.translate("MainWindow", "Donate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_Steam_Account_Name.setText(QtGui.QApplication.translate("MainWindow", "Set Steam Account Name", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCinema_Mode.setText(QtGui.QApplication.translate("MainWindow", "Cinema Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUninstall_Current.setText(QtGui.QApplication.translate("MainWindow", "Uninstall Current", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Skins_Folder.setText(QtGui.QApplication.translate("MainWindow", "Open Skins Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
import icons_rc
