# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scgui.ui'
#
# Created: Fri Feb 17 14:41:41 2012
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(350, 460)
        MainWindow.setMinimumSize(QtCore.QSize(350, 460))
        MainWindow.setMaximumSize(QtCore.QSize(350, 460))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/counterstrike-5.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 335, 405))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.skinsTab = QtGui.QWidget()
        self.skinsTab.setObjectName(_fromUtf8("skinsTab"))
        self.BTN_uninstallSkin = QtGui.QPushButton(self.skinsTab)
        self.BTN_uninstallSkin.setEnabled(True)
        self.BTN_uninstallSkin.setGeometry(QtCore.QRect(260, 209, 61, 23))
        self.BTN_uninstallSkin.setAutoFillBackground(False)
        self.BTN_uninstallSkin.setCheckable(False)
        self.BTN_uninstallSkin.setObjectName(_fromUtf8("BTN_uninstallSkin"))
        self.BTN_skinFolder = QtGui.QPushButton(self.skinsTab)
        self.BTN_skinFolder.setGeometry(QtCore.QRect(110, 350, 61, 23))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/folders_explorer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_skinFolder.setIcon(icon1)
        self.BTN_skinFolder.setObjectName(_fromUtf8("BTN_skinFolder"))
        self.comboBox_skins = QtGui.QComboBox(self.skinsTab)
        self.comboBox_skins.setGeometry(QtCore.QRect(70, 180, 181, 21))
        self.comboBox_skins.setObjectName(_fromUtf8("comboBox_skins"))
        self.skinName = QtGui.QLabel(self.skinsTab)
        self.skinName.setGeometry(QtCore.QRect(10, 10, 311, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.skinName.setFont(font)
        self.skinName.setObjectName(_fromUtf8("skinName"))
        self.skinDescription = QtGui.QLabel(self.skinsTab)
        self.skinDescription.setGeometry(QtCore.QRect(10, 250, 311, 91))
        self.skinDescription.setTextFormat(QtCore.Qt.PlainText)
        self.skinDescription.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.skinDescription.setWordWrap(True)
        self.skinDescription.setMargin(0)
        self.skinDescription.setIndent(-1)
        self.skinDescription.setOpenExternalLinks(False)
        self.skinDescription.setObjectName(_fromUtf8("skinDescription"))
        self.skinAuthor = QtGui.QLabel(self.skinsTab)
        self.skinAuthor.setGeometry(QtCore.QRect(10, 30, 311, 20))
        font = QtGui.QFont()
        font.setItalic(False)
        self.skinAuthor.setFont(font)
        self.skinAuthor.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.skinAuthor.setWordWrap(False)
        self.skinAuthor.setObjectName(_fromUtf8("skinAuthor"))
        self.skinVersion = QtGui.QLabel(self.skinsTab)
        self.skinVersion.setGeometry(QtCore.QRect(70, 200, 181, 21))
        self.skinVersion.setObjectName(_fromUtf8("skinVersion"))
        self.skinVersionLabel = QtGui.QLabel(self.skinsTab)
        self.skinVersionLabel.setGeometry(QtCore.QRect(10, 200, 51, 21))
        self.skinVersionLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.skinVersionLabel.setObjectName(_fromUtf8("skinVersionLabel"))
        self.skinTypeLabel = QtGui.QLabel(self.skinsTab)
        self.skinTypeLabel.setGeometry(QtCore.QRect(10, 220, 51, 21))
        self.skinTypeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.skinTypeLabel.setObjectName(_fromUtf8("skinTypeLabel"))
        self.skinType = QtGui.QLabel(self.skinsTab)
        self.skinType.setGeometry(QtCore.QRect(70, 220, 181, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.skinType.setFont(font)
        self.skinType.setFocusPolicy(QtCore.Qt.NoFocus)
        self.skinType.setToolTip(_fromUtf8(""))
        self.skinType.setStatusTip(_fromUtf8(""))
        self.skinType.setScaledContents(False)
        self.skinType.setOpenExternalLinks(False)
        self.skinType.setObjectName(_fromUtf8("skinType"))
        self.SkinPreviewImage = QtGui.QLabel(self.skinsTab)
        self.SkinPreviewImage.setGeometry(QtCore.QRect(10, 50, 311, 121))
        self.SkinPreviewImage.setAutoFillBackground(False)
        self.SkinPreviewImage.setFrameShape(QtGui.QFrame.NoFrame)
        self.SkinPreviewImage.setFrameShadow(QtGui.QFrame.Plain)
        self.SkinPreviewImage.setLineWidth(0)
        self.SkinPreviewImage.setText(_fromUtf8(""))
        self.SkinPreviewImage.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/default.jpg")))
        self.SkinPreviewImage.setScaledContents(True)
        self.SkinPreviewImage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SkinPreviewImage.setObjectName(_fromUtf8("SkinPreviewImage"))
        self.BTN_installSkin = QtGui.QPushButton(self.skinsTab)
        self.BTN_installSkin.setEnabled(True)
        self.BTN_installSkin.setGeometry(QtCore.QRect(260, 179, 61, 23))
        self.BTN_installSkin.setAutoFillBackground(False)
        self.BTN_installSkin.setCheckable(False)
        self.BTN_installSkin.setObjectName(_fromUtf8("BTN_installSkin"))
        self.BTN_cstrikeFolder = QtGui.QPushButton(self.skinsTab)
        self.BTN_cstrikeFolder.setGeometry(QtCore.QRect(180, 350, 61, 23))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_cstrikeFolder.setIcon(icon2)
        self.BTN_cstrikeFolder.setObjectName(_fromUtf8("BTN_cstrikeFolder"))
        self.skinNameLabel = QtGui.QLabel(self.skinsTab)
        self.skinNameLabel.setGeometry(QtCore.QRect(10, 180, 51, 20))
        self.skinNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.skinNameLabel.setObjectName(_fromUtf8("skinNameLabel"))
        self.BTN_launchCSSpec = QtGui.QPushButton(self.skinsTab)
        self.BTN_launchCSSpec.setGeometry(QtCore.QRect(10, 350, 91, 23))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/movies.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_launchCSSpec.setIcon(icon3)
        self.BTN_launchCSSpec.setObjectName(_fromUtf8("BTN_launchCSSpec"))
        self.tabWidget.addTab(self.skinsTab, _fromUtf8(""))
        self.configTab = QtGui.QWidget()
        self.configTab.setObjectName(_fromUtf8("configTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.configTab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.configTable = QtGui.QTableView(self.configTab)
        self.configTable.setEnabled(False)
        self.configTable.setObjectName(_fromUtf8("configTable"))
        self.verticalLayout_3.addWidget(self.configTable)
        self.BTN_updateCfg = QtGui.QPushButton(self.configTab)
        self.BTN_updateCfg.setEnabled(False)
        self.BTN_updateCfg.setObjectName(_fromUtf8("BTN_updateCfg"))
        self.verticalLayout_3.addWidget(self.BTN_updateCfg)
        self.tabWidget.addTab(self.configTab, _fromUtf8(""))
        self.teamsTab = QtGui.QWidget()
        self.teamsTab.setObjectName(_fromUtf8("teamsTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.teamsTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_t1 = QtGui.QGroupBox(self.teamsTab)
        self.groupBox_t1.setEnabled(False)
        self.groupBox_t1.setObjectName(_fromUtf8("groupBox_t1"))
        self.Box_t1name = QtGui.QLineEdit(self.groupBox_t1)
        self.Box_t1name.setGeometry(QtCore.QRect(82, 20, 211, 20))
        self.Box_t1name.setToolTip(_fromUtf8(""))
        self.Box_t1name.setWhatsThis(_fromUtf8(""))
        self.Box_t1name.setObjectName(_fromUtf8("Box_t1name"))
        self.t1nameLabel = QtGui.QLabel(self.groupBox_t1)
        self.t1nameLabel.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.t1nameLabel.setObjectName(_fromUtf8("t1nameLabel"))
        self.Box_t1url = QtGui.QLineEdit(self.groupBox_t1)
        self.Box_t1url.setGeometry(QtCore.QRect(82, 50, 211, 20))
        self.Box_t1url.setObjectName(_fromUtf8("Box_t1url"))
        self.t1urlLabel = QtGui.QLabel(self.groupBox_t1)
        self.t1urlLabel.setGeometry(QtCore.QRect(10, 50, 61, 21))
        self.t1urlLabel.setObjectName(_fromUtf8("t1urlLabel"))
        self.comboBox_t1flag = QtGui.QComboBox(self.groupBox_t1)
        self.comboBox_t1flag.setGeometry(QtCore.QRect(80, 80, 211, 22))
        self.comboBox_t1flag.setObjectName(_fromUtf8("comboBox_t1flag"))
        self.t1flagLabel = QtGui.QLabel(self.groupBox_t1)
        self.t1flagLabel.setGeometry(QtCore.QRect(10, 80, 61, 21))
        self.t1flagLabel.setObjectName(_fromUtf8("t1flagLabel"))
        self.verticalLayout_2.addWidget(self.groupBox_t1)
        self.groupBox_t2 = QtGui.QGroupBox(self.teamsTab)
        self.groupBox_t2.setEnabled(False)
        self.groupBox_t2.setObjectName(_fromUtf8("groupBox_t2"))
        self.Box_t2name = QtGui.QLineEdit(self.groupBox_t2)
        self.Box_t2name.setGeometry(QtCore.QRect(82, 20, 211, 20))
        self.Box_t2name.setObjectName(_fromUtf8("Box_t2name"))
        self.t2nameLabel = QtGui.QLabel(self.groupBox_t2)
        self.t2nameLabel.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.t2nameLabel.setObjectName(_fromUtf8("t2nameLabel"))
        self.Box_t2url = QtGui.QLineEdit(self.groupBox_t2)
        self.Box_t2url.setGeometry(QtCore.QRect(82, 50, 211, 20))
        self.Box_t2url.setObjectName(_fromUtf8("Box_t2url"))
        self.t2urlLabel = QtGui.QLabel(self.groupBox_t2)
        self.t2urlLabel.setGeometry(QtCore.QRect(10, 50, 61, 21))
        self.t2urlLabel.setObjectName(_fromUtf8("t2urlLabel"))
        self.comboBox_t2flag = QtGui.QComboBox(self.groupBox_t2)
        self.comboBox_t2flag.setGeometry(QtCore.QRect(80, 80, 211, 22))
        self.comboBox_t2flag.setObjectName(_fromUtf8("comboBox_t2flag"))
        self.t2flagLabel = QtGui.QLabel(self.groupBox_t2)
        self.t2flagLabel.setGeometry(QtCore.QRect(10, 80, 61, 21))
        self.t2flagLabel.setObjectName(_fromUtf8("t2flagLabel"))
        self.verticalLayout_2.addWidget(self.groupBox_t2)
        self.BTN_swapSides = QtGui.QPushButton(self.teamsTab)
        self.BTN_swapSides.setEnabled(False)
        self.BTN_swapSides.setObjectName(_fromUtf8("BTN_swapSides"))
        self.verticalLayout_2.addWidget(self.BTN_swapSides)
        self.BTN_updateTeams = QtGui.QPushButton(self.teamsTab)
        self.BTN_updateTeams.setEnabled(False)
        self.BTN_updateTeams.setObjectName(_fromUtf8("BTN_updateTeams"))
        self.verticalLayout_2.addWidget(self.BTN_updateTeams)
        self.tabWidget.addTab(self.teamsTab, _fromUtf8(""))
        self.updateTab = QtGui.QWidget()
        self.updateTab.setObjectName(_fromUtf8("updateTab"))
        self.devWeb = QtWebKit.QWebView(self.updateTab)
        self.devWeb.setGeometry(QtCore.QRect(10, 10, 311, 331))
        self.devWeb.setUrl(QtCore.QUrl(_fromUtf8("http://www.scgui.com/tagged/update/mobile")))
        self.devWeb.setZoomFactor(0.600000023842)
        self.devWeb.setObjectName(_fromUtf8("devWeb"))
        self.tabWidget.addTab(self.updateTab, _fromUtf8(""))
        self.settingsTab = QtGui.QWidget()
        self.settingsTab.setObjectName(_fromUtf8("settingsTab"))
        self.groupBox = QtGui.QGroupBox(self.settingsTab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 311, 131))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.steamlabel = QtGui.QLabel(self.groupBox)
        self.steamlabel.setGeometry(QtCore.QRect(10, 20, 231, 16))
        self.steamlabel.setObjectName(_fromUtf8("steamlabel"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setEnabled(False)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 231, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.comboBox_2 = QtGui.QComboBox(self.groupBox)
        self.comboBox_2.setEnabled(False)
        self.comboBox_2.setGeometry(QtCore.QRect(10, 90, 291, 21))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.BTN_steamname = QtGui.QPushButton(self.groupBox)
        self.BTN_steamname.setGeometry(QtCore.QRect(234, 39, 71, 23))
        self.BTN_steamname.setObjectName(_fromUtf8("BTN_steamname"))
        self.steaminput = QtGui.QLineEdit(self.groupBox)
        self.steaminput.setGeometry(QtCore.QRect(10, 40, 221, 21))
        self.steaminput.setObjectName(_fromUtf8("steaminput"))
        self.groupBox_2 = QtGui.QGroupBox(self.settingsTab)
        self.groupBox_2.setGeometry(QtCore.QRect(9, 149, 311, 121))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(10, 40, 291, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 80, 291, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/gear_in.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.settingsTab, icon4, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Config = QtGui.QAction(MainWindow)
        self.actionLoad_Config.setEnabled(False)
        self.actionLoad_Config.setObjectName(_fromUtf8("actionLoad_Config"))
        self.actionSave_Config = QtGui.QAction(MainWindow)
        self.actionSave_Config.setEnabled(False)
        self.actionSave_Config.setObjectName(_fromUtf8("actionSave_Config"))
        self.actionCheck_for_Updates = QtGui.QAction(MainWindow)
        self.actionCheck_for_Updates.setEnabled(False)
        self.actionCheck_for_Updates.setObjectName(_fromUtf8("actionCheck_for_Updates"))
        self.actionWebsite = QtGui.QAction(MainWindow)
        self.actionWebsite.setObjectName(_fromUtf8("actionWebsite"))
        self.actionPrefrences = QtGui.QAction(MainWindow)
        self.actionPrefrences.setObjectName(_fromUtf8("actionPrefrences"))
        self.actionDevelopers_Blog = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/tumblr.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDevelopers_Blog.setIcon(icon5)
        self.actionDevelopers_Blog.setObjectName(_fromUtf8("actionDevelopers_Blog"))
        self.actionDonate = QtGui.QAction(MainWindow)
        self.actionDonate.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/award_star_gold_3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDonate.setIcon(icon6)
        self.actionDonate.setObjectName(_fromUtf8("actionDonate"))
        self.actionSet_Steam_Account_Name = QtGui.QAction(MainWindow)
        self.actionSet_Steam_Account_Name.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/steam_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSet_Steam_Account_Name.setIcon(icon7)
        self.actionSet_Steam_Account_Name.setObjectName(_fromUtf8("actionSet_Steam_Account_Name"))
        self.actionCinema_Mode = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/hd_720.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCinema_Mode.setIcon(icon8)
        self.actionCinema_Mode.setObjectName(_fromUtf8("actionCinema_Mode"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionUninstall_Current = QtGui.QAction(MainWindow)
        self.actionUninstall_Current.setObjectName(_fromUtf8("actionUninstall_Current"))
        self.actionOpen_Skins_Folder = QtGui.QAction(MainWindow)
        self.actionOpen_Skins_Folder.setObjectName(_fromUtf8("actionOpen_Skins_Folder"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionLoad_Config)
        self.menuFile.addAction(self.actionSave_Config)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionWebsite)
        self.menuHelp.addAction(self.actionDevelopers_Blog)
        self.menuHelp.addAction(self.actionDonate)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setStatusTip(QtGui.QApplication.translate("MainWindow", "Please visit scgui.com and DONATE!", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_uninstallSkin.setToolTip(QtGui.QApplication.translate("MainWindow", "Remove the current skin", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_uninstallSkin.setStatusTip(QtGui.QApplication.translate("MainWindow", "Remove the current skin", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_uninstallSkin.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_skinFolder.setToolTip(QtGui.QApplication.translate("MainWindow", "Open the skins folder in Explorer", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_skinFolder.setStatusTip(QtGui.QApplication.translate("MainWindow", "Open the skins folder in Explorer", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_skinFolder.setText(QtGui.QApplication.translate("MainWindow", "Skins", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_skins.setToolTip(QtGui.QApplication.translate("MainWindow", "Choose a skin from this menu", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_skins.setStatusTip(QtGui.QApplication.translate("MainWindow", "Choose a skin from this menu", None, QtGui.QApplication.UnicodeUTF8))
        self.skinName.setText(QtGui.QApplication.translate("MainWindow", "Base", None, QtGui.QApplication.UnicodeUTF8))
        self.skinDescription.setText(QtGui.QApplication.translate("MainWindow", "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", None, QtGui.QApplication.UnicodeUTF8))
        self.skinAuthor.setText(QtGui.QApplication.translate("MainWindow", "author", None, QtGui.QApplication.UnicodeUTF8))
        self.skinVersion.setText(QtGui.QApplication.translate("MainWindow", "version", None, QtGui.QApplication.UnicodeUTF8))
        self.skinVersionLabel.setText(QtGui.QApplication.translate("MainWindow", "Version", None, QtGui.QApplication.UnicodeUTF8))
        self.skinTypeLabel.setText(QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.skinType.setText(QtGui.QApplication.translate("MainWindow", "type", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_installSkin.setToolTip(QtGui.QApplication.translate("MainWindow", "Click to install the selected skin", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_installSkin.setStatusTip(QtGui.QApplication.translate("MainWindow", "Click to install the selected skin", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_installSkin.setText(QtGui.QApplication.translate("MainWindow", "Install", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_cstrikeFolder.setToolTip(QtGui.QApplication.translate("MainWindow", "Open your cstrike folder in explorer", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_cstrikeFolder.setStatusTip(QtGui.QApplication.translate("MainWindow", "Open your cstrike folder in explorer", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_cstrikeFolder.setText(QtGui.QApplication.translate("MainWindow", "cstrike", None, QtGui.QApplication.UnicodeUTF8))
        self.skinNameLabel.setText(QtGui.QApplication.translate("MainWindow", "Skin", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_launchCSSpec.setToolTip(QtGui.QApplication.translate("MainWindow", "Launch CS:Source in Movie Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_launchCSSpec.setStatusTip(QtGui.QApplication.translate("MainWindow", "Launch CS:Source in Movie Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_launchCSSpec.setText(QtGui.QApplication.translate("MainWindow", "Launch CS", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.skinsTab), QtGui.QApplication.translate("MainWindow", "Skins", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_updateCfg.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.configTab), QtGui.QApplication.translate("MainWindow", "Config", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_t1.setTitle(QtGui.QApplication.translate("MainWindow", "Home Team", None, QtGui.QApplication.UnicodeUTF8))
        self.Box_t1name.setStatusTip(QtGui.QApplication.translate("MainWindow", "Enter the Counter-Terrorist team name", None, QtGui.QApplication.UnicodeUTF8))
        self.t1nameLabel.setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.Box_t1url.setStatusTip(QtGui.QApplication.translate("MainWindow", "Enter the text you want under the team name", None, QtGui.QApplication.UnicodeUTF8))
        self.t1urlLabel.setText(QtGui.QApplication.translate("MainWindow", "Website", None, QtGui.QApplication.UnicodeUTF8))
        self.t1flagLabel.setText(QtGui.QApplication.translate("MainWindow", "Flag/Logo", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_t2.setTitle(QtGui.QApplication.translate("MainWindow", "Away Team", None, QtGui.QApplication.UnicodeUTF8))
        self.Box_t2name.setStatusTip(QtGui.QApplication.translate("MainWindow", "Enter the Terrorist team name", None, QtGui.QApplication.UnicodeUTF8))
        self.t2nameLabel.setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.Box_t2url.setStatusTip(QtGui.QApplication.translate("MainWindow", "Enter the text you want under the team name", None, QtGui.QApplication.UnicodeUTF8))
        self.t2urlLabel.setText(QtGui.QApplication.translate("MainWindow", "Website", None, QtGui.QApplication.UnicodeUTF8))
        self.t2flagLabel.setText(QtGui.QApplication.translate("MainWindow", "Flag/Logo", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_swapSides.setText(QtGui.QApplication.translate("MainWindow", "Swap Teams / Half Time", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_updateTeams.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.teamsTab), QtGui.QApplication.translate("MainWindow", "Teams", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.updateTab), QtGui.QApplication.translate("MainWindow", "Updates", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Game Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.steamlabel.setText(QtGui.QApplication.translate("MainWindow", "Steam Account Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Supported Game", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(0, QtGui.QApplication.translate("MainWindow", "Counter-Strike: Source", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_steamname.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Registration", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Config.setText(QtGui.QApplication.translate("MainWindow", "Load Config", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Config.setText(QtGui.QApplication.translate("MainWindow", "Save Config", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCheck_for_Updates.setText(QtGui.QApplication.translate("MainWindow", "Check for Updates", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWebsite.setText(QtGui.QApplication.translate("MainWindow", "Website", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrefrences.setText(QtGui.QApplication.translate("MainWindow", "Steam Name", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDevelopers_Blog.setText(QtGui.QApplication.translate("MainWindow", "Developers Blog", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDonate.setText(QtGui.QApplication.translate("MainWindow", "Donate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_Steam_Account_Name.setText(QtGui.QApplication.translate("MainWindow", "Set Steam Account Name", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCinema_Mode.setText(QtGui.QApplication.translate("MainWindow", "Cinema Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUninstall_Current.setText(QtGui.QApplication.translate("MainWindow", "Uninstall Current", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Skins_Folder.setText(QtGui.QApplication.translate("MainWindow", "Open Skins Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
import icons_rc
