# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scgui.ui'
#
# Created: Thu Feb 16 16:55:41 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(350, 460)
        MainWindow.setMinimumSize(QtCore.QSize(350, 460))
        MainWindow.setMaximumSize(QtCore.QSize(350, 460))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/counterstrike-5.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 335, 405))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.skinsTab = QtGui.QWidget()
        self.skinsTab.setObjectName(_fromUtf8("skinsTab"))
        self.BTN_uninstallSkin = QtGui.QPushButton(self.skinsTab)
        self.BTN_uninstallSkin.setEnabled(True)
        self.BTN_uninstallSkin.setGeometry(QtCore.QRect(260, 350, 61, 23))
        self.BTN_uninstallSkin.setAutoFillBackground(False)
        self.BTN_uninstallSkin.setCheckable(False)
        self.BTN_uninstallSkin.setObjectName(_fromUtf8("BTN_uninstallSkin"))
        self.BTN_skinFolder = QtGui.QPushButton(self.skinsTab)
        self.BTN_skinFolder.setGeometry(QtCore.QRect(10, 350, 101, 23))
        self.BTN_skinFolder.setObjectName(_fromUtf8("BTN_skinFolder"))
        self.comboBox_skins = QtGui.QComboBox(self.skinsTab)
        self.comboBox_skins.setGeometry(QtCore.QRect(220, 10, 101, 22))
        self.comboBox_skins.setObjectName(_fromUtf8("comboBox_skins"))
        self.skinName = QtGui.QLabel(self.skinsTab)
        self.skinName.setGeometry(QtCore.QRect(10, 10, 191, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.skinName.setFont(font)
        self.skinName.setObjectName(_fromUtf8("skinName"))
        self.skinDescription = QtGui.QLabel(self.skinsTab)
        self.skinDescription.setGeometry(QtCore.QRect(70, 240, 241, 91))
        self.skinDescription.setTextFormat(QtCore.Qt.PlainText)
        self.skinDescription.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.skinDescription.setWordWrap(True)
        self.skinDescription.setMargin(0)
        self.skinDescription.setIndent(-1)
        self.skinDescription.setOpenExternalLinks(False)
        self.skinDescription.setObjectName(_fromUtf8("skinDescription"))
        self.skinAuthorLabel = QtGui.QLabel(self.skinsTab)
        self.skinAuthorLabel.setGeometry(QtCore.QRect(10, 170, 51, 20))
        self.skinAuthorLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.skinAuthorLabel.setObjectName(_fromUtf8("skinAuthorLabel"))
        self.skinAuthor = QtGui.QLabel(self.skinsTab)
        self.skinAuthor.setGeometry(QtCore.QRect(70, 170, 111, 20))
        self.skinAuthor.setObjectName(_fromUtf8("skinAuthor"))
        self.skinVersion = QtGui.QLabel(self.skinsTab)
        self.skinVersion.setGeometry(QtCore.QRect(70, 190, 181, 20))
        self.skinVersion.setObjectName(_fromUtf8("skinVersion"))
        self.skinVersionLabel = QtGui.QLabel(self.skinsTab)
        self.skinVersionLabel.setGeometry(QtCore.QRect(10, 190, 51, 20))
        self.skinVersionLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.skinVersionLabel.setObjectName(_fromUtf8("skinVersionLabel"))
        self.skinWebsiteLabel = QtGui.QLabel(self.skinsTab)
        self.skinWebsiteLabel.setGeometry(QtCore.QRect(10, 210, 51, 20))
        self.skinWebsiteLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.skinWebsiteLabel.setObjectName(_fromUtf8("skinWebsiteLabel"))
        self.skinWebsite = QtGui.QLabel(self.skinsTab)
        self.skinWebsite.setGeometry(QtCore.QRect(70, 210, 241, 20))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.skinWebsite.setFont(font)
        self.skinWebsite.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.skinWebsite.setFocusPolicy(QtCore.Qt.NoFocus)
        self.skinWebsite.setStyleSheet(_fromUtf8("color: rgb(85, 0, 255);\n"
"text-decoration:underline;"))
        self.skinWebsite.setScaledContents(False)
        self.skinWebsite.setOpenExternalLinks(False)
        self.skinWebsite.setObjectName(_fromUtf8("skinWebsite"))
        self.skinInfoLabel = QtGui.QLabel(self.skinsTab)
        self.skinInfoLabel.setGeometry(QtCore.QRect(10, 240, 51, 20))
        self.skinInfoLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.skinInfoLabel.setObjectName(_fromUtf8("skinInfoLabel"))
        self.SkinPreviewImage = QtGui.QLabel(self.skinsTab)
        self.SkinPreviewImage.setGeometry(QtCore.QRect(10, 40, 311, 121))
        self.SkinPreviewImage.setAutoFillBackground(False)
        self.SkinPreviewImage.setFrameShape(QtGui.QFrame.StyledPanel)
        self.SkinPreviewImage.setFrameShadow(QtGui.QFrame.Sunken)
        self.SkinPreviewImage.setText(_fromUtf8(""))
        self.SkinPreviewImage.setScaledContents(True)
        self.SkinPreviewImage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SkinPreviewImage.setObjectName(_fromUtf8("SkinPreviewImage"))
        self.BTN_installSkin = QtGui.QPushButton(self.skinsTab)
        self.BTN_installSkin.setEnabled(True)
        self.BTN_installSkin.setGeometry(QtCore.QRect(170, 350, 81, 23))
        self.BTN_installSkin.setAutoFillBackground(False)
        self.BTN_installSkin.setCheckable(False)
        self.BTN_installSkin.setObjectName(_fromUtf8("BTN_installSkin"))
        self.tabWidget.addTab(self.skinsTab, _fromUtf8(""))
        self.configTab = QtGui.QWidget()
        self.configTab.setObjectName(_fromUtf8("configTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.configTab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.configTable = QtGui.QTableView(self.configTab)
        self.configTable.setObjectName(_fromUtf8("configTable"))
        self.verticalLayout_3.addWidget(self.configTable)
        self.BTN_updateCfg = QtGui.QPushButton(self.configTab)
        self.BTN_updateCfg.setObjectName(_fromUtf8("BTN_updateCfg"))
        self.verticalLayout_3.addWidget(self.BTN_updateCfg)
        self.tabWidget.addTab(self.configTab, _fromUtf8(""))
        self.teamsTab = QtGui.QWidget()
        self.teamsTab.setObjectName(_fromUtf8("teamsTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.teamsTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_t1 = QtGui.QGroupBox(self.teamsTab)
        self.groupBox_t1.setEnabled(True)
        self.groupBox_t1.setObjectName(_fromUtf8("groupBox_t1"))
        self.Box_t1name = QtGui.QLineEdit(self.groupBox_t1)
        self.Box_t1name.setGeometry(QtCore.QRect(82, 20, 211, 20))
        self.Box_t1name.setToolTip(_fromUtf8(""))
        self.Box_t1name.setWhatsThis(_fromUtf8(""))
        self.Box_t1name.setObjectName(_fromUtf8("Box_t1name"))
        self.t1nameLabel = QtGui.QLabel(self.groupBox_t1)
        self.t1nameLabel.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.t1nameLabel.setObjectName(_fromUtf8("t1nameLabel"))
        self.Box_t1url = QtGui.QLineEdit(self.groupBox_t1)
        self.Box_t1url.setGeometry(QtCore.QRect(82, 50, 211, 20))
        self.Box_t1url.setObjectName(_fromUtf8("Box_t1url"))
        self.t1urlLabel = QtGui.QLabel(self.groupBox_t1)
        self.t1urlLabel.setGeometry(QtCore.QRect(10, 50, 61, 21))
        self.t1urlLabel.setObjectName(_fromUtf8("t1urlLabel"))
        self.comboBox_t1flag = QtGui.QComboBox(self.groupBox_t1)
        self.comboBox_t1flag.setGeometry(QtCore.QRect(80, 80, 211, 22))
        self.comboBox_t1flag.setObjectName(_fromUtf8("comboBox_t1flag"))
        self.t1flagLabel = QtGui.QLabel(self.groupBox_t1)
        self.t1flagLabel.setGeometry(QtCore.QRect(10, 80, 61, 21))
        self.t1flagLabel.setObjectName(_fromUtf8("t1flagLabel"))
        self.verticalLayout_2.addWidget(self.groupBox_t1)
        self.groupBox_t2 = QtGui.QGroupBox(self.teamsTab)
        self.groupBox_t2.setEnabled(True)
        self.groupBox_t2.setObjectName(_fromUtf8("groupBox_t2"))
        self.Box_t2name = QtGui.QLineEdit(self.groupBox_t2)
        self.Box_t2name.setGeometry(QtCore.QRect(82, 20, 211, 20))
        self.Box_t2name.setObjectName(_fromUtf8("Box_t2name"))
        self.t2nameLabel = QtGui.QLabel(self.groupBox_t2)
        self.t2nameLabel.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.t2nameLabel.setObjectName(_fromUtf8("t2nameLabel"))
        self.Box_t2url = QtGui.QLineEdit(self.groupBox_t2)
        self.Box_t2url.setGeometry(QtCore.QRect(82, 50, 211, 20))
        self.Box_t2url.setObjectName(_fromUtf8("Box_t2url"))
        self.t2urlLabel = QtGui.QLabel(self.groupBox_t2)
        self.t2urlLabel.setGeometry(QtCore.QRect(10, 50, 61, 21))
        self.t2urlLabel.setObjectName(_fromUtf8("t2urlLabel"))
        self.comboBox_t2flag = QtGui.QComboBox(self.groupBox_t2)
        self.comboBox_t2flag.setGeometry(QtCore.QRect(80, 80, 211, 22))
        self.comboBox_t2flag.setObjectName(_fromUtf8("comboBox_t2flag"))
        self.t2flagLabel = QtGui.QLabel(self.groupBox_t2)
        self.t2flagLabel.setGeometry(QtCore.QRect(10, 80, 61, 21))
        self.t2flagLabel.setObjectName(_fromUtf8("t2flagLabel"))
        self.verticalLayout_2.addWidget(self.groupBox_t2)
        self.BTN_swapSides = QtGui.QPushButton(self.teamsTab)
        self.BTN_swapSides.setObjectName(_fromUtf8("BTN_swapSides"))
        self.verticalLayout_2.addWidget(self.BTN_swapSides)
        self.BTN_updateTeams = QtGui.QPushButton(self.teamsTab)
        self.BTN_updateTeams.setObjectName(_fromUtf8("BTN_updateTeams"))
        self.verticalLayout_2.addWidget(self.BTN_updateTeams)
        self.tabWidget.addTab(self.teamsTab, _fromUtf8(""))
        self.updateTab = QtGui.QWidget()
        self.updateTab.setObjectName(_fromUtf8("updateTab"))
        self.devWeb = QtWebKit.QWebView(self.updateTab)
        self.devWeb.setGeometry(QtCore.QRect(10, 10, 311, 331))
        self.devWeb.setUrl(QtCore.QUrl(_fromUtf8("http://www.scgui.com/tagged/update/mobile")))
        self.devWeb.setZoomFactor(0.600000023842)
        self.devWeb.setObjectName(_fromUtf8("devWeb"))
        self.tabWidget.addTab(self.updateTab, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuLaunch_CS_Source = QtGui.QMenu(self.menuTools)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/Counter-Strike-Source.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuLaunch_CS_Source.setIcon(icon1)
        self.menuLaunch_CS_Source.setObjectName(_fromUtf8("menuLaunch_CS_Source"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Config = QtGui.QAction(MainWindow)
        self.actionLoad_Config.setEnabled(False)
        self.actionLoad_Config.setObjectName(_fromUtf8("actionLoad_Config"))
        self.actionSave_Config = QtGui.QAction(MainWindow)
        self.actionSave_Config.setEnabled(False)
        self.actionSave_Config.setObjectName(_fromUtf8("actionSave_Config"))
        self.actionCheck_for_Updates = QtGui.QAction(MainWindow)
        self.actionCheck_for_Updates.setEnabled(False)
        self.actionCheck_for_Updates.setObjectName(_fromUtf8("actionCheck_for_Updates"))
        self.actionWebsite = QtGui.QAction(MainWindow)
        self.actionWebsite.setObjectName(_fromUtf8("actionWebsite"))
        self.actionPrefrences = QtGui.QAction(MainWindow)
        self.actionPrefrences.setObjectName(_fromUtf8("actionPrefrences"))
        self.actionDevelopers_Blog = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/tumblr.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDevelopers_Blog.setIcon(icon2)
        self.actionDevelopers_Blog.setObjectName(_fromUtf8("actionDevelopers_Blog"))
        self.actionDonate = QtGui.QAction(MainWindow)
        self.actionDonate.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/award_star_gold_3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDonate.setIcon(icon3)
        self.actionDonate.setObjectName(_fromUtf8("actionDonate"))
        self.actionSet_Steam_Account_Name = QtGui.QAction(MainWindow)
        self.actionSet_Steam_Account_Name.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/steam_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSet_Steam_Account_Name.setIcon(icon4)
        self.actionSet_Steam_Account_Name.setObjectName(_fromUtf8("actionSet_Steam_Account_Name"))
        self.actionCinema_Mode = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/hd_720.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCinema_Mode.setIcon(icon5)
        self.actionCinema_Mode.setObjectName(_fromUtf8("actionCinema_Mode"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionUninstall_Current = QtGui.QAction(MainWindow)
        self.actionUninstall_Current.setObjectName(_fromUtf8("actionUninstall_Current"))
        self.actionOpen_Skins_Folder = QtGui.QAction(MainWindow)
        self.actionOpen_Skins_Folder.setObjectName(_fromUtf8("actionOpen_Skins_Folder"))
        self.menuFile.addAction(self.actionLoad_Config)
        self.menuFile.addAction(self.actionSave_Config)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuLaunch_CS_Source.addSeparator()
        self.menuLaunch_CS_Source.addAction(self.actionCinema_Mode)
        self.menuTools.addAction(self.menuLaunch_CS_Source.menuAction())
        self.menuTools.addAction(self.actionSet_Steam_Account_Name)
        self.menuTools.addSeparator()
        self.menuHelp.addAction(self.actionWebsite)
        self.menuHelp.addAction(self.actionDevelopers_Blog)
        self.menuHelp.addAction(self.actionDonate)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "SCGUI Beta", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_uninstallSkin.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_skinFolder.setToolTip(QtGui.QApplication.translate("MainWindow", "Open the skins folder in Explorer", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_skinFolder.setText(QtGui.QApplication.translate("MainWindow", "Open Skins Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.skinName.setText(QtGui.QApplication.translate("MainWindow", "Base", None, QtGui.QApplication.UnicodeUTF8))
        self.skinDescription.setText(QtGui.QApplication.translate("MainWindow", "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", None, QtGui.QApplication.UnicodeUTF8))
        self.skinAuthorLabel.setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.skinAuthor.setText(QtGui.QApplication.translate("MainWindow", "Edward Knowles", None, QtGui.QApplication.UnicodeUTF8))
        self.skinVersion.setText(QtGui.QApplication.translate("MainWindow", "1.0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.skinVersionLabel.setText(QtGui.QApplication.translate("MainWindow", "Version", None, QtGui.QApplication.UnicodeUTF8))
        self.skinWebsiteLabel.setText(QtGui.QApplication.translate("MainWindow", "Website", None, QtGui.QApplication.UnicodeUTF8))
        self.skinWebsite.setToolTip(QtGui.QApplication.translate("MainWindow", "Click here to visit the authors website", None, QtGui.QApplication.UnicodeUTF8))
        self.skinWebsite.setStatusTip(QtGui.QApplication.translate("MainWindow", "Visit the authors website", None, QtGui.QApplication.UnicodeUTF8))
        self.skinWebsite.setText(QtGui.QApplication.translate("MainWindow", "http://www.example.com", None, QtGui.QApplication.UnicodeUTF8))
        self.skinInfoLabel.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_installSkin.setText(QtGui.QApplication.translate("MainWindow", "Install", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.skinsTab), QtGui.QApplication.translate("MainWindow", "Skins", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_updateCfg.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.configTab), QtGui.QApplication.translate("MainWindow", "Config", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_t1.setTitle(QtGui.QApplication.translate("MainWindow", "Home Team", None, QtGui.QApplication.UnicodeUTF8))
        self.Box_t1name.setStatusTip(QtGui.QApplication.translate("MainWindow", "Enter the Counter-Terrorist team name", None, QtGui.QApplication.UnicodeUTF8))
        self.t1nameLabel.setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.Box_t1url.setStatusTip(QtGui.QApplication.translate("MainWindow", "Enter the text you want under the team name", None, QtGui.QApplication.UnicodeUTF8))
        self.t1urlLabel.setText(QtGui.QApplication.translate("MainWindow", "Website", None, QtGui.QApplication.UnicodeUTF8))
        self.t1flagLabel.setText(QtGui.QApplication.translate("MainWindow", "Flag/Logo", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_t2.setTitle(QtGui.QApplication.translate("MainWindow", "Away Team", None, QtGui.QApplication.UnicodeUTF8))
        self.Box_t2name.setStatusTip(QtGui.QApplication.translate("MainWindow", "Enter the Terrorist team name", None, QtGui.QApplication.UnicodeUTF8))
        self.t2nameLabel.setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.Box_t2url.setStatusTip(QtGui.QApplication.translate("MainWindow", "Enter the text you want under the team name", None, QtGui.QApplication.UnicodeUTF8))
        self.t2urlLabel.setText(QtGui.QApplication.translate("MainWindow", "Website", None, QtGui.QApplication.UnicodeUTF8))
        self.t2flagLabel.setText(QtGui.QApplication.translate("MainWindow", "Flag/Logo", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_swapSides.setText(QtGui.QApplication.translate("MainWindow", "Swap Teams / Half Time", None, QtGui.QApplication.UnicodeUTF8))
        self.BTN_updateTeams.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.teamsTab), QtGui.QApplication.translate("MainWindow", "Teams", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.updateTab), QtGui.QApplication.translate("MainWindow", "Updates", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLaunch_CS_Source.setTitle(QtGui.QApplication.translate("MainWindow", "Launch CS:Source", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Config.setText(QtGui.QApplication.translate("MainWindow", "Load Config", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Config.setText(QtGui.QApplication.translate("MainWindow", "Save Config", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCheck_for_Updates.setText(QtGui.QApplication.translate("MainWindow", "Check for Updates", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWebsite.setText(QtGui.QApplication.translate("MainWindow", "Website", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrefrences.setText(QtGui.QApplication.translate("MainWindow", "Steam Name", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDevelopers_Blog.setText(QtGui.QApplication.translate("MainWindow", "Developers Blog", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDonate.setText(QtGui.QApplication.translate("MainWindow", "Donate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_Steam_Account_Name.setText(QtGui.QApplication.translate("MainWindow", "Set Steam Account Name", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCinema_Mode.setText(QtGui.QApplication.translate("MainWindow", "Cinema Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUninstall_Current.setText(QtGui.QApplication.translate("MainWindow", "Uninstall Current", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Skins_Folder.setText(QtGui.QApplication.translate("MainWindow", "Open Skins Folder", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
import icons_rc
